; LLVM-M0 hand-authored fixture from restructuring_lab.dll / flat_branchless_synth.
; This is not generated by a d810 lifter.  It models the GLBOPT1 branchless
; next-state select observed in tools/hexrays_structuring_lab/observations:
;   mask = -(token & 1)
;   state = (K1 & mask) | (K2 & ~mask)
; and enough surrounding value code to expose the same token+0x11 / -0x33
; residue described by samples/restructuring_lab/specs/L8-conditional-synthesis.md.
source_filename = "lab_flat_branchless.m0"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "x86_64-pc-windows-msvc"

@state_sink = external global i32
@value_sink = external global i32

define i32 @lab_flat_branchless_m0(i32 %token) {
entry:
  %low = and i32 %token, 1
  %mask = sub i32 0, %low
  %not_mask = xor i32 %mask, -1

  %state_true = and i32 -1188804898, %mask
  %state_false = and i32 1015636137, %not_mask
  %state = or i32 %state_true, %state_false
  store volatile i32 %state, ptr @state_sink

  %base = add i32 %token, 17
  %true_value = xor i32 %base, 34
  %false_value = add i32 %base, -51
  %true_part = and i32 %true_value, %mask
  %false_part = and i32 %false_value, %not_mask
  %value = or i32 %true_part, %false_part
  store volatile i32 %value, ptr @value_sink

  ret i32 %value
}
