"""LLVM text emitter backend over portable d810 IR.

This package is intentionally IDA-free.  It consumes ``d810.ir`` records and
emits textual LLVM IR for the narrow M1a supported subset.
"""
from __future__ import annotations

from .emitter import (
    LlvmIdentityManifest,
    LlvmLiftResult,
    UnsupportedLiftKind,
    UnsupportedLiftReason,
    emit_flowgraph_to_llvm,
)
from .identity_lowering import (
    LlvmIdentityManifestBlock,
    LlvmIdentityManifestControl,
    LlvmIdentityManifestEffect,
    LlvmIdentityManifestInstruction,
    LlvmIdentityManifestMemory,
    LlvmIdentityManifestSwitchCase,
    LlvmIdentityManifestVarnode,
    LlvmIdentityMismatch,
    LlvmIdentityParityResult,
    LlvmIdentityParityStatus,
    check_identity_manifest,
    check_identity_roundtrip,
)
from .lower_back_contract import (
    LlvmEdgeMove,
    LlvmLowerBackBlock,
    LlvmLowerBackFunction,
    LlvmLowerBackInstruction,
    LlvmLowerBackPlan,
    LlvmLowerBackResult,
    LlvmLowerBackStatus,
    LlvmLowerBackTerminator,
    LlvmLowerBackTerminatorKind,
    LlvmLowerBackUnsupportedKind,
    LlvmLowerBackUnsupportedReason,
    LlvmPhiIncoming,
    LlvmPhiNode,
    LlvmValueRef,
    plan_lower_back,
)
from .maturity_policy import (
    LLVM_M1_ACCEPTED_MATURITIES,
    LLVM_M1_PREFERRED_MATURITY,
    LlvmMaturityAssessment,
    assess_flowgraph_maturity,
)
from .optimization import (
    LLVM_M2A_STOCK_PIPELINE,
    LlvmIrMetrics,
    LlvmOptimizationResult,
    LlvmOptimizationStatus,
    LlvmOptPipeline,
    measure_llvm_ir,
    normalize_llvm_ir,
    run_llvm_opt_pipeline,
)
from .verification import (
    LlvmVerificationResult,
    LlvmVerificationStatus,
    find_llvm_opt,
    verify_llvm_ir,
)

__all__ = [
    "LLVM_M1_ACCEPTED_MATURITIES",
    "LLVM_M1_PREFERRED_MATURITY",
    "LLVM_M2A_STOCK_PIPELINE",
    "LlvmIdentityManifest",
    "LlvmIdentityManifestBlock",
    "LlvmIdentityManifestControl",
    "LlvmIdentityManifestEffect",
    "LlvmIdentityManifestInstruction",
    "LlvmIdentityManifestMemory",
    "LlvmIdentityManifestSwitchCase",
    "LlvmIdentityManifestVarnode",
    "LlvmIdentityMismatch",
    "LlvmIdentityParityResult",
    "LlvmIdentityParityStatus",
    "LlvmLiftResult",
    "LlvmEdgeMove",
    "LlvmLowerBackBlock",
    "LlvmLowerBackFunction",
    "LlvmLowerBackInstruction",
    "LlvmLowerBackPlan",
    "LlvmLowerBackResult",
    "LlvmLowerBackStatus",
    "LlvmLowerBackTerminator",
    "LlvmLowerBackTerminatorKind",
    "LlvmLowerBackUnsupportedKind",
    "LlvmLowerBackUnsupportedReason",
    "LlvmMaturityAssessment",
    "LlvmIrMetrics",
    "LlvmOptimizationResult",
    "LlvmOptimizationStatus",
    "LlvmOptPipeline",
    "LlvmVerificationResult",
    "LlvmVerificationStatus",
    "LlvmPhiIncoming",
    "LlvmPhiNode",
    "LlvmValueRef",
    "UnsupportedLiftKind",
    "UnsupportedLiftReason",
    "assess_flowgraph_maturity",
    "check_identity_manifest",
    "check_identity_roundtrip",
    "emit_flowgraph_to_llvm",
    "find_llvm_opt",
    "measure_llvm_ir",
    "normalize_llvm_ir",
    "plan_lower_back",
    "run_llvm_opt_pipeline",
    "verify_llvm_ir",
]
