#!/usr/bin/env python3
"""Portable-core shape-lint GATE (warning-mode ratchet) -- epic llr-rv7p, S8.

The ``portable-core-no-ida`` import-linter contract forbids ``import ida_*`` but
canNOT see SHAPE: pure-Python code under ``ir / analyses / transforms / passes /
capabilities / families`` can pass the import gate while mirroring the Hex-Rays
data model (duck-typed ``getattr(x, "t")`` mop reads, ``"m_<op>"`` opcode-string
dispatch, ``maturity:int`` plumbing, ``serial`` identity fields, ...).

``tools/scripts/codemod_portable_ir_audit.py`` is the deterministic, read-only,
AST-based DETECTOR for those leaks (categories A/B/C/D/E).  THIS script wraps it
as a CI/pre-commit RATCHET:

  * It re-measures the live per-category counts.
  * It compares them against a committed BASELINE
    (``tools/scripts/portable_shape_lint_baseline.json``).
  * WARNING MODE (default, this is the S8 deliverable): existing baseline leaks
    are REPORTED but do NOT fail the build; the gate fails ONLY when a category
    count INCREASES above its baseline (i.e. a NEW leak was introduced).
  * The baseline can be refreshed with ``--update-baseline`` (use this to RATCHET
    DOWN after fixing leaks -- never to ratchet up).

Per the ticket: land warning-mode after S1/S4, flip to error-mode after S5/S6.
The ``--strict`` flag is the forward seam for that flip (it additionally fails if
*any* tracked category is still above zero); it is NOT wired into CI yet.

Stdlib-only and deterministic, exactly like the detector it wraps -- no network,
no third-party deps, no writes unless ``--update-baseline`` is passed.

Exit codes:
  0  gate clean (warning-mode: no category exceeds baseline)
  1  REGRESSION: a category count rose above baseline (or, with --strict, a
     tracked category is non-zero)
  2  usage / baseline-file error
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import pathlib
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[2]
_CODEMOD_PATH = pathlib.Path(__file__).resolve().parent / "codemod_portable_ir_audit.py"
BASELINE_PATH = (
    pathlib.Path(__file__).resolve().parent / "portable_shape_lint_baseline.json"
)

_CATEGORIES = ("A", "B", "C", "D", "E")
_CAT_NAME = {
    "A": "maturity",
    "B": "serial-identity",
    "C": "mop/duck-typed",
    "D": "stale-refs",
    "E": "opcode-dispatch",
}


def _load_codemod():
    """Import the read-only detector as a module (registers it in sys.modules so
    its ``frozen=True`` dataclasses resolve their string annotations)."""
    spec = importlib.util.spec_from_file_location(
        "codemod_portable_ir_audit", _CODEMOD_PATH
    )
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"cannot load detector at {_CODEMOD_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("codemod_portable_ir_audit", module)
    spec.loader.exec_module(module)
    return module


def measure() -> dict[str, dict[str, int]]:
    """Return ``{cat: {"all": n, "real_leak": n}}`` for every category."""
    codemod = _load_codemod()
    findings = []
    for path in codemod._iter_targets(codemod.PORTABLE_CORE):
        rel = str(path.relative_to(codemod.ROOT))
        findings.extend(codemod._audit_file(path, rel))
    by_all = Counter(f.category for f in findings)
    by_real = Counter(f.category for f in findings if f.verdict == "REAL-LEAK")
    return {
        cat: {"all": int(by_all.get(cat, 0)), "real_leak": int(by_real.get(cat, 0))}
        for cat in _CATEGORIES
    }


def _baseline_payload(counts: dict[str, dict[str, int]]) -> dict:
    return {
        "_comment": (
            "Per-category portable-core shape-lint baseline (epic llr-rv7p, S8). "
            "Generated by tools/scripts/portable_shape_lint_gate.py --update-baseline. "
            "Gate is WARNING-MODE: fails only if a category count rises above these "
            "numbers. Ratchet DOWN after fixing leaks; never up."
        ),
        "categories": counts,
    }


def load_baseline() -> dict[str, dict[str, int]]:
    if not BASELINE_PATH.exists():
        raise FileNotFoundError(
            f"baseline file missing: {BASELINE_PATH} (run with --update-baseline to seed)"
        )
    data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    cats = data.get("categories", {})
    out: dict[str, dict[str, int]] = {}
    for cat in _CATEGORIES:
        entry = cats.get(cat, {})
        out[cat] = {
            "all": int(entry.get("all", 0)),
            "real_leak": int(entry.get("real_leak", 0)),
        }
    return out


def _print_table(
    current: dict[str, dict[str, int]], baseline: dict[str, dict[str, int]]
) -> None:
    print(
        "# Portable-core shape-lint gate (warning-mode ratchet) -- epic llr-rv7p S8\n"
    )
    print("|cat|name|REAL base|REAL now|delta|all base|all now|delta|")
    print("|-|-|-|-|-|-|-|-|")
    for cat in _CATEGORIES:
        rb = baseline[cat]["real_leak"]
        rn = current[cat]["real_leak"]
        ab = baseline[cat]["all"]
        an = current[cat]["all"]
        print(f"|{cat}|{_CAT_NAME[cat]}|{rb}|{rn}|{rn - rb:+d}|{ab}|{an}|{an - ab:+d}|")
    print()


def _regressions(
    current: dict[str, dict[str, int]], baseline: dict[str, dict[str, int]]
) -> list[str]:
    """A regression is a REAL-LEAK count that ROSE above its baseline."""
    out: list[str] = []
    for cat in _CATEGORIES:
        rn = current[cat]["real_leak"]
        rb = baseline[cat]["real_leak"]
        if rn > rb:
            out.append(
                f"category {cat} ({_CAT_NAME[cat]}): REAL-LEAK {rn} > baseline {rb} "
                f"(+{rn - rb}) -- NEW portable-core shape leak introduced"
            )
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--update-baseline",
        action="store_true",
        help="rewrite the committed baseline JSON with current counts (ratchet)",
    )
    ap.add_argument(
        "--strict",
        action="store_true",
        help="error-mode seam (S5/S6): also fail if any tracked category is non-zero",
    )
    ap.add_argument(
        "--json", action="store_true", help="machine-readable counts + verdict"
    )
    args = ap.parse_args(argv)

    current = measure()

    if args.update_baseline:
        BASELINE_PATH.write_text(
            json.dumps(_baseline_payload(current), indent=2) + "\n", encoding="utf-8"
        )
        print(f"baseline updated: {BASELINE_PATH.relative_to(ROOT)}")
        if not args.json:
            _print_table(current, current)
        return 0

    try:
        baseline = load_baseline()
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    regressions = _regressions(current, baseline)
    strict_violations: list[str] = []
    if args.strict:
        for cat in _CATEGORIES:
            if current[cat]["real_leak"] > 0:
                strict_violations.append(
                    f"category {cat} ({_CAT_NAME[cat]}): {current[cat]['real_leak']} "
                    f"REAL-LEAK remaining (strict/error-mode)"
                )

    failed = bool(regressions) or bool(strict_violations)

    if args.json:
        print(
            json.dumps(
                {
                    "current": current,
                    "baseline": baseline,
                    "regressions": regressions,
                    "strict_violations": strict_violations,
                    "mode": "strict" if args.strict else "warning",
                    "passed": not failed,
                },
                indent=2,
            )
        )
    else:
        _print_table(current, baseline)
        if regressions:
            print("REGRESSIONS (gate FAILS -- new leaks above baseline):")
            for line in regressions:
                print(f"  FAIL  {line}")
        elif args.strict and strict_violations:
            print(
                "STRICT VIOLATIONS (error-mode -- tracked categories must reach zero):"
            )
            for line in strict_violations:
                print(f"  FAIL  {line}")
        else:
            mode = "strict/error-mode" if args.strict else "warning-mode"
            print(
                f"OK ({mode}): no category exceeds baseline. "
                "Existing baseline leaks are reported above but do NOT block the build."
            )

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
