"""Compatibility import for the neutral legacy metadata key owner."""

from d810.core.legacy_keys import (
    CONCRETE_STATE_ROUTE_PROVENANCE_METADATA,
    DETACHED_DEAD_HANDLER_COMPONENT_METADATA,
    DISPATCHER_CORRIDOR_COVERAGE_METADATA,
    DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA,
    EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA,
    FULL_UNFLATTENING_CLAIM_METADATA,
    LEGACY_FAMILY_DETAIL_CODES,
    LEGACY_UNFLATTEN_KEYS,
    NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA,
    UNFLATTEN_COMPLETION_STATUS_METADATA,
    USE_DEF_SEVERANCE_AUDIT_METADATA,
)

__all__ = [
    "CONCRETE_STATE_ROUTE_PROVENANCE_METADATA",
    "DETACHED_DEAD_HANDLER_COMPONENT_METADATA",
    "DISPATCHER_CORRIDOR_COVERAGE_METADATA",
    "DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA",
    "EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA",
    "FULL_UNFLATTENING_CLAIM_METADATA",
    "LEGACY_FAMILY_DETAIL_CODES",
    "LEGACY_UNFLATTEN_KEYS",
    "NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA",
    "UNFLATTEN_COMPLETION_STATUS_METADATA",
    "USE_DEF_SEVERANCE_AUDIT_METADATA",
]
