"""Neutral ownership for legacy unflatten metadata keys."""

from __future__ import annotations

from types import MappingProxyType

DISPATCHER_CORRIDOR_COVERAGE_METADATA = "dispatcher_corridor_coverage"
DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA = "dispatcher_removal_preflight_proof"
UNFLATTEN_COMPLETION_STATUS_METADATA = "unflatten_completion_status"
FULL_UNFLATTENING_CLAIM_METADATA = "full_unflattening_claim"
USE_DEF_SEVERANCE_AUDIT_METADATA = "use_def_severance_audit"
EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA = (
    "exact_state_branch_effect_exclusions"
)
CONCRETE_STATE_ROUTE_PROVENANCE_METADATA = "concrete_state_route_provenance"
NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA = (
    "native_bound_transition_route_receipts"
)

LEGACY_UNFLATTEN_KEYS = frozenset(
    {
        DISPATCHER_CORRIDOR_COVERAGE_METADATA,
        DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA,
        UNFLATTEN_COMPLETION_STATUS_METADATA,
        FULL_UNFLATTENING_CLAIM_METADATA,
        USE_DEF_SEVERANCE_AUDIT_METADATA,
        EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA,
        CONCRETE_STATE_ROUTE_PROVENANCE_METADATA,
        NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA,
    }
)

LEGACY_FAMILY_DETAIL_CODES = MappingProxyType({
    EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA: "legacy_exact_effect_not_enabled",
    FULL_UNFLATTENING_CLAIM_METADATA: "legacy_retirement_not_enabled",
    DISPATCHER_CORRIDOR_COVERAGE_METADATA: "legacy_corridor_not_enabled",
    DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA: "legacy_corridor_not_enabled",
    USE_DEF_SEVERANCE_AUDIT_METADATA: "legacy_corridor_not_enabled",
    CONCRETE_STATE_ROUTE_PROVENANCE_METADATA: "legacy_route_not_enabled",
    NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA: "legacy_route_not_enabled",
    UNFLATTEN_COMPLETION_STATUS_METADATA: "legacy_terminal_cycle_not_enabled",
})

__all__ = [
    "CONCRETE_STATE_ROUTE_PROVENANCE_METADATA",
    "DISPATCHER_CORRIDOR_COVERAGE_METADATA",
    "DISPATCHER_REMOVAL_PREFLIGHT_PROOF_METADATA",
    "EXACT_STATE_BRANCH_EFFECT_EXCLUSIONS_METADATA",
    "FULL_UNFLATTENING_CLAIM_METADATA",
    "LEGACY_FAMILY_DETAIL_CODES",
    "LEGACY_UNFLATTEN_KEYS",
    "NATIVE_BOUND_TRANSITION_ROUTE_RECEIPTS_METADATA",
    "UNFLATTEN_COMPLETION_STATUS_METADATA",
    "USE_DEF_SEVERANCE_AUDIT_METADATA",
]
