"""Safe diagnostic event bus and snapshot-ref machinery for runtime
domain observations.

This module is the foundation of the event-refactor follow-on plan
(see ``docs/diag-observability-boundary.md``). Runtime publishes
domain observation events on the bus; diagnostic subscribers
installed in :mod:`d810.core.diag.event_handlers` consume them and
persist rows to the SQLite diag DB. The runtime never holds a
SQLite ``snapshot_id``; it works in terms of :class:`SnapshotRef`,
which the subscriber maps to a row id.

Design constraints
------------------

- This module has zero dependencies on :mod:`d810.core.diag`. It uses
  only stdlib plus :mod:`d810.core.logging` and :mod:`d810.core.typing`.
- Subscriber exceptions are caught, logged via :mod:`d810.core.logging`,
  and never propagated. Diagnostic failures must not change optimizer
  behavior.
- The bus is process-global. Tests must call :func:`reset_diagnostic_bus`
  in a fixture to keep handler state clean.
"""
from __future__ import annotations

import dataclasses
import threading
import uuid

from d810.core import logging as _d810_logging
from d810.core.typing import Any, Callable

_logger = _d810_logging.getLogger("D810.observability")


@dataclasses.dataclass(frozen=True)
class SnapshotRef:
    """Opaque handle to a runtime snapshot capture.

    Runtime code receives a :class:`SnapshotRef` from
    :func:`d810.hexrays.observability.capture_mba_snapshot` (or an
    equivalent recon-domain entry point) and passes it to every
    follow-on event emit that targets the same snapshot. The diag
    subscriber maps ``key`` to the SQLite ``snapshots.id`` it
    inserted.

    ``key`` is opaque to runtime code. It is generated by the bus
    (or by the capture API) and is guaranteed to be unique for the
    lifetime of one diag session.
    """

    key: str
    func_ea: int
    label: str
    maturity: str
    phase: str


def new_snapshot_key() -> str:
    """Mint a fresh opaque :class:`SnapshotRef` key.

    Used by capture-side APIs (or tests) that build a ``SnapshotRef``
    without an existing key. Returns a uuid4 hex string.
    """
    return uuid.uuid4().hex


# ---------------------------------------------------------------------------
# Event bus
# ---------------------------------------------------------------------------

# Subscribers register against an event TYPE (typically a frozen
# dataclass class object). When ``emit(event)`` is called, the bus
# looks up handlers registered for ``type(event)`` and invokes each
# with the event instance. Multiple handlers per type are allowed and
# fire in insertion order.

_lock = threading.Lock()
_subscribers: dict[type, list[Callable[[Any], None]]] = {}


def subscribe(event_type: type, handler: Callable[[Any], None]) -> None:
    """Register ``handler`` to receive events of ``event_type``.

    Handlers may be registered multiple times; each registration adds
    a separate invocation on :func:`emit`. Use
    :func:`unsubscribe` to remove a specific handler.
    """
    with _lock:
        _subscribers.setdefault(event_type, []).append(handler)


def unsubscribe(event_type: type, handler: Callable[[Any], None]) -> None:
    """Remove ``handler`` from the subscriber list for ``event_type``.

    Removes one occurrence (the first match). No-op if the handler is
    not registered.
    """
    with _lock:
        handlers = _subscribers.get(event_type)
        if not handlers:
            return
        try:
            handlers.remove(handler)
        except ValueError:
            return
        if not handlers:
            _subscribers.pop(event_type, None)


def reset_diagnostic_bus() -> None:
    """Drop all subscribers. Test harness use only.

    Production code should call :func:`unsubscribe` per handler so the
    bus state remains predictable across the full process lifetime.
    """
    with _lock:
        _subscribers.clear()


def has_subscribers(event_type: type) -> bool:
    """Return True if at least one handler is registered for ``event_type``."""
    with _lock:
        return bool(_subscribers.get(event_type))


def emit(event: Any) -> None:
    """Dispatch ``event`` to every subscriber of ``type(event)``.

    Subscriber exceptions are caught and logged at WARNING level; they
    do not propagate. This is a hard invariant: diagnostic failures
    must never change optimizer behavior.
    """
    event_type = type(event)
    with _lock:
        handlers = list(_subscribers.get(event_type, ()))
    if not handlers:
        return
    for handler in handlers:
        try:
            handler(event)
        except Exception:
            _logger.warning(
                "diagnostic subscriber raised on event %s (handler=%r); swallowed",
                event_type.__name__,
                handler,
                exc_info=True,
            )


__all__ = [
    "SnapshotRef",
    "emit",
    "has_subscribers",
    "new_snapshot_key",
    "reset_diagnostic_bus",
    "subscribe",
    "unsubscribe",
]
