"""Safe diagnostic event bus and snapshot-ref machinery for runtime
domain observations.

This module is the foundation of the event-refactor follow-on plan
(see ``docs/diag-observability-boundary.md``). Runtime publishes
domain observation events on the bus; diagnostic subscribers
installed in :mod:`d810.core.diag.event_handlers` consume them and
persist rows to the SQLite diag DB. The runtime never holds a
SQLite ``snapshot_id``; it works in terms of :class:`SnapshotRef`,
which the subscriber maps to a row id.

Design constraints
------------------

- This module has zero dependencies on :mod:`d810.core.diag`. It uses
  only stdlib plus :mod:`d810.core.logging` and :mod:`d810.core.typing`.
- Subscriber exceptions are caught, logged via :mod:`d810.core.logging`,
  and never propagated. Diagnostic failures must not change optimizer
  behavior.
- The bus is process-global. Tests must call :func:`reset_diagnostic_bus`
  in a fixture to keep handler state clean.
"""
from __future__ import annotations

import dataclasses
import threading
import uuid

from d810.core import logging as _d810_logging
from d810.core.typing import Any, Callable

_logger = _d810_logging.getLogger("D810.observability")


@dataclasses.dataclass(frozen=True)
class SnapshotRef:
    """Opaque handle to a runtime snapshot capture.

    Runtime code receives a :class:`SnapshotRef` from
    :func:`d810.hexrays.observability.capture_mba_snapshot` (or an
    equivalent recon-domain entry point) and passes it to every
    follow-on event emit that targets the same snapshot. The diag
    subscriber maps ``key`` to the SQLite ``snapshots.id`` it
    inserted.

    ``key`` is opaque to runtime code. It is generated by the bus
    (or by the capture API) and is guaranteed to be unique for the
    lifetime of one diag session.
    """

    key: str
    func_ea: int
    label: str
    maturity: str
    phase: str


def new_snapshot_key() -> str:
    """Mint a fresh opaque :class:`SnapshotRef` key.

    Used by capture-side APIs (or tests) that build a ``SnapshotRef``
    without an existing key. Returns a uuid4 hex string.
    """
    return uuid.uuid4().hex


# ---------------------------------------------------------------------------
# Event bus
# ---------------------------------------------------------------------------

# Subscribers register against an event TYPE (typically a frozen
# dataclass class object). When ``emit(event)`` is called, the bus
# looks up handlers registered for ``type(event)`` and invokes each
# with the event instance. Multiple handlers per type are allowed and
# fire in insertion order.

_lock = threading.Lock()
_subscribers: dict[type, list[Callable[[Any], None]]] = {}


def subscribe(event_type: type, handler: Callable[[Any], None]) -> None:
    """Register ``handler`` to receive events of ``event_type``.

    Handlers may be registered multiple times; each registration adds
    a separate invocation on :func:`emit`. Use
    :func:`unsubscribe` to remove a specific handler.
    """
    with _lock:
        _subscribers.setdefault(event_type, []).append(handler)


def unsubscribe(event_type: type, handler: Callable[[Any], None]) -> None:
    """Remove ``handler`` from the subscriber list for ``event_type``.

    Removes one occurrence (the first match). No-op if the handler is
    not registered.
    """
    with _lock:
        handlers = _subscribers.get(event_type)
        if not handlers:
            return
        try:
            handlers.remove(handler)
        except ValueError:
            return
        if not handlers:
            _subscribers.pop(event_type, None)


def reset_diagnostic_bus() -> None:
    """Drop all subscribers. Test harness use only.

    Production code should call :func:`unsubscribe` per handler so the
    bus state remains predictable across the full process lifetime.
    """
    with _lock:
        _subscribers.clear()


def has_subscribers(event_type: type) -> bool:
    """Return True if at least one handler is registered for ``event_type``."""
    with _lock:
        return bool(_subscribers.get(event_type))


def emit(event: Any) -> None:
    """Dispatch ``event`` to every subscriber of ``type(event)``.

    Subscriber exceptions are caught and logged at WARNING level; they
    do not propagate. This is a hard invariant: diagnostic failures
    must never change optimizer behavior.
    """
    event_type = type(event)
    with _lock:
        handlers = list(_subscribers.get(event_type, ()))
    if not handlers:
        return
    for handler in handlers:
        try:
            handler(event)
        except Exception:
            _logger.warning(
                "diagnostic subscriber raised on event %s (handler=%r); swallowed",
                event_type.__name__,
                handler,
                exc_info=True,
            )


# ---------------------------------------------------------------------------
# Diagnostic backend registration (dependency inversion)
#
# Runtime layers (manager, recon, cfg, hexrays, optimizers) MUST NOT
# import ``d810.core.diag`` directly -- not even via importlib. They
# operate against the abstract interface declared here:
#
#   - ``open_observability_session(func_ea)`` / ``close_observability_session()``
#   - ``get_active_diag_conn(func_ea=0)``
#
# The diag SQLite backend lives in ``d810.core.diag`` and registers
# itself at module load via :func:`register_diag_session_handlers` and
# :func:`register_diag_conn_provider`. ``core.observability`` lives in
# the same package layer as ``core.diag`` so the (one-time, lazy)
# importlib bootstrap below does not cross any layer boundary or
# violate the runtime-no-core-diag contract.
# ---------------------------------------------------------------------------

_session_lock = threading.Lock()
_session_open_handler: Callable[[int], None] | None = None
_session_close_handler: Callable[[], None] | None = None
_diag_conn_provider: Callable[..., Any] | None = None


def register_diag_session_handlers(
    open_fn: Callable[[int], None],
    close_fn: Callable[[], None],
) -> None:
    """Register the open/close handlers for the diag backend.

    Called by ``d810.core.diag.__init__`` at module load. Idempotent;
    a second call replaces the previous handlers.
    """
    global _session_open_handler, _session_close_handler
    with _session_lock:
        _session_open_handler = open_fn
        _session_close_handler = close_fn


def register_diag_conn_provider(fn: Callable[..., Any]) -> None:
    """Register the active-connection provider for the diag backend.

    The callable receives ``(func_ea: int = 0)`` and returns the active
    SQLite connection or ``None``. Called by ``d810.core.diag.__init__``
    at module load.
    """
    global _diag_conn_provider
    with _session_lock:
        _diag_conn_provider = fn


def _ensure_backend_loaded() -> None:
    """Lazy-import the diag backend so it has a chance to register.

    Runtime layers only call into ``core.observability``; nothing else
    imports ``core.diag`` statically. This bootstrap triggers
    registration on first use of the backend.

    ``importlib`` stays in ``core.observability`` (same package layer as
    ``core.diag``) and never reaches into a runtime module's import
    graph.
    """
    if _diag_conn_provider is not None and _session_open_handler is not None:
        return
    import importlib
    try:
        importlib.import_module("d810.core.diag")
    except Exception:
        pass


def open_observability_session(func_ea: int) -> None:
    """Open the diag session bound to ``func_ea``.

    Triggers backend bootstrap on first call. No-op when no backend
    has registered handlers (e.g. ``diag_snapshots`` setting disabled).
    """
    _ensure_backend_loaded()
    handler = _session_open_handler
    if handler is None:
        return
    try:
        handler(int(func_ea))
    except Exception:
        _logger.warning(
            "diag session open handler raised; swallowed (func_ea=0x%x)",
            int(func_ea),
            exc_info=True,
        )


def close_observability_session() -> None:
    """Close the active diag session, if any.

    Backend-agnostic; the registered close handler tears down the
    SQLite connection and unsubscribes the event handlers.
    """
    handler = _session_close_handler
    if handler is None:
        return
    try:
        handler()
    except Exception:
        _logger.warning(
            "diag session close handler raised; swallowed", exc_info=True,
        )


def get_active_diag_conn(func_ea: int = 0) -> Any:
    """Return the active diag SQLite connection or ``None``.

    Lazy-loads the backend on first call. This is the canonical
    interface for read-side behavior bridges (e.g.
    ``byte_emit_tail_isolation_runtime``) that legitimately need to
    query persisted diag rows to drive runtime decisions.
    """
    _ensure_backend_loaded()
    provider = _diag_conn_provider
    if provider is None:
        return None
    try:
        return provider(int(func_ea))
    except Exception:
        _logger.warning(
            "diag conn provider raised; treating as no conn (func_ea=0x%x)",
            int(func_ea),
            exc_info=True,
        )
        return None


__all__ = [
    "SnapshotRef",
    "close_observability_session",
    "emit",
    "get_active_diag_conn",
    "has_subscribers",
    "new_snapshot_key",
    "open_observability_session",
    "register_diag_conn_provider",
    "register_diag_session_handlers",
    "reset_diagnostic_bus",
    "subscribe",
    "unsubscribe",
]
