"""Corridor liveness policy — decide whether shortcutting over witness blocks is legal.

Branch witnesses prove which dispatcher arm is feasible.  This module decides
whether bypassing the selected witness corridor would sever a live non-state
use-def chain.  The state variable itself is intentionally severed by the
unflattening and is ignored.
"""
from __future__ import annotations

from dataclasses import dataclass

from d810.analyses.control_flow.branch_witness import (
    BranchWitnessAbstain,
    BranchWitnessConflict,
)
from d810.core import logging

logger = logging.getLogger("D810.transforms.corridor_liveness_policy")


@dataclass(frozen=True, slots=True)
class CorridorShortcutDecision:
    """Decision for shortcutting over an exact branch-witness corridor."""

    allowed: bool
    reason: str
    corridor_blocks: tuple[int, ...] = ()


def _int_or_none(value: object) -> int | None:
    try:
        return int(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


def _variable_key(operand: object) -> tuple[str, int] | None:
    """Canonical identity for a directly named non-state operand."""
    if operand is None:
        return None
    stkoff = _int_or_none(getattr(operand, "stkoff", None))
    if stkoff is not None:
        return ("stk", int(stkoff))
    reg = _int_or_none(getattr(operand, "reg", None))
    if reg is not None:
        return ("reg", int(reg))
    refs = getattr(operand, "stack_refs", ()) or ()
    if refs:
        return ("stk", int(refs[0]))
    return None


def _variable_keys(operand: object) -> set[tuple[str, int]]:
    """All variable identities read by ``operand``, including nested sub-insns."""
    found: set[tuple[str, int]] = set()
    seen: set[int] = set()

    def _walk(cur: object) -> None:
        if cur is None:
            return
        ident = id(cur)
        if ident in seen:
            return
        seen.add(ident)
        key = _variable_key(cur)
        if key is not None:
            found.add(key)
        for stkoff in getattr(cur, "stack_refs", ()) or ():
            found.add(("stk", int(stkoff)))
        for attr in ("sub_l", "sub_r", "sub_operand"):
            _walk(getattr(cur, attr, None))
        sub_insn = getattr(cur, "sub_instruction", None)
        if sub_insn is not None:
            _walk(getattr(sub_insn, "l", None))
            _walk(getattr(sub_insn, "r", None))
            # Function-call argument lists can hide additional register/stack uses.
            dest = getattr(sub_insn, "d", None)
            for arg in getattr(dest, "args", ()) or ():
                _walk(arg)

    _walk(operand)
    return found


def _block_gen_kill(block: object, state_var_stkoff: int | None):
    """Return (gen, kill) variable sets for one block.

    A stack/register location is killed by a definition (``d`` operand) and
    generated by a use (``l`` or ``r`` operand).  The state variable is excluded
    from both sets.
    """
    gen: set[tuple[str, int]] = set()
    kill: set[tuple[str, int]] = set()
    state_key: tuple[str, int] | None = None
    if state_var_stkoff is not None:
        state_key = ("stk", int(state_var_stkoff))

    for insn in getattr(block, "insn_snapshots", ()) or ():
        # Uses first (a use in the same instruction is not killed by its own def).
        for operand in (getattr(insn, "l", None), getattr(insn, "r", None)):
            for key in _variable_keys(operand):
                if key != state_key:
                    gen.add(key)
        dest = getattr(insn, "d", None)
        key = _variable_key(dest)
        if key is not None and key != state_key:
            kill.add(key)
    return gen, kill


def _compute_liveness(
    flow_graph: object,
    state_var_stkoff: int | None,
) -> dict[int, set[tuple[str, int]]]:
    """Backward dataflow: live-in variables per block."""
    blocks: dict[int, object] = {}
    for serial in getattr(flow_graph, "blocks", ()):
        block = flow_graph.get_block(serial)
        if block is not None:
            blocks[int(serial)] = block

    gen: dict[int, set[tuple[str, int]]] = {}
    kill: dict[int, set[tuple[str, int]]] = {}
    for serial, block in blocks.items():
        g, k = _block_gen_kill(block, state_var_stkoff)
        gen[serial] = g
        kill[serial] = k

    live_in: dict[int, set[tuple[str, int]]] = {serial: set() for serial in blocks}
    live_out: dict[int, set[tuple[str, int]]] = {serial: set() for serial in blocks}

    changed = True
    while changed:
        changed = False
        for serial in blocks:
            new_out: set[tuple[str, int]] = set()
            for succ in getattr(blocks[serial], "succs", ()):
                succ_i = int(succ)
                if succ_i in live_in:
                    new_out |= live_in[succ_i]
            if new_out != live_out[serial]:
                live_out[serial] = new_out
                changed = True
            new_in = (new_out - kill[serial]) | gen[serial]
            if new_in != live_in[serial]:
                live_in[serial] = new_in
                changed = True

    return live_in


def block_defined_variables(
    block: object,
    state_var_stkoff: int | None,
) -> set[tuple[str, int]]:
    """Return non-state variables directly defined by ``block``."""
    _gen, kill = _block_gen_kill(block, state_var_stkoff)
    return set(kill)


def live_in_variables(
    flow_graph: object,
    state_var_stkoff: int | None,
) -> dict[int, set[tuple[str, int]]]:
    """Return live-in variables per block."""
    return _compute_liveness(flow_graph, state_var_stkoff)


def corridor_shortcut_is_live_safe(
    flow_graph: object,
    witness_path: tuple[object, ...],
    shortcut_target: int,
    state_var_stkoff: int | None,
) -> bool:
    """Return ``True`` if bypassing ``witness_path`` blocks is use-def safe.

    A non-state variable defined in the witness corridor is unsafe to bypass if
    it is live at the entry of ``shortcut_target``.  The state variable is the
    unflattening target and is never counted.
    """
    live_in = _compute_liveness(flow_graph, state_var_stkoff)
    target_live = live_in.get(int(shortcut_target), set())
    if not target_live:
        return True

    state_key: tuple[str, int] | None = None
    if state_var_stkoff is not None:
        state_key = ("stk", int(state_var_stkoff))

    corridor_defs: set[tuple[str, int]] = set()
    for witness in witness_path:
        compare_serial = _int_or_none(getattr(witness, "compare_block", None))
        if compare_serial is None:
            continue
        block = flow_graph.get_block(compare_serial)
        if block is None:
            continue
        _gen, kill = _block_gen_kill(block, state_var_stkoff)
        corridor_defs |= kill

    unsafe = corridor_defs & target_live
    if unsafe and logger.debug_on:
        logger.debug(
            "corridor liveness rejects shortcut to blk[%d]: live variables %s "
            "defined in corridor %s",
            int(shortcut_target),
            sorted(unsafe),
            [getattr(w, "compare_block", None) for w in witness_path],
        )
    return not unsafe


def evaluate_corridor_shortcut(
    flow_graph: object,
    witness_result: object,
    shortcut_target: int,
    state_var_stkoff: int | None,
) -> CorridorShortcutDecision:
    """Apply shortcut legality after branch feasibility has been proven.

    Branch-witness resolution is the feasibility policy.  This function consumes
    its exact/abstain/conflict result and then applies the liveness policy as a
    second, independent gate.
    """
    if isinstance(witness_result, BranchWitnessAbstain):
        return CorridorShortcutDecision(
            allowed=False,
            reason=f"witness_abstain:{witness_result.reason}",
        )
    if isinstance(witness_result, BranchWitnessConflict):
        return CorridorShortcutDecision(
            allowed=False,
            reason="witness_conflict",
        )

    witness_path = tuple(witness_result) if witness_result is not None else ()
    corridor_blocks = tuple(
        int(compare_block)
        for witness in witness_path
        for compare_block in (_int_or_none(getattr(witness, "compare_block", None)),)
        if compare_block is not None
    )
    if not witness_path:
        return CorridorShortcutDecision(
            allowed=False,
            reason="empty_witness_path",
            corridor_blocks=corridor_blocks,
        )
    if not corridor_shortcut_is_live_safe(
        flow_graph, witness_path, int(shortcut_target), state_var_stkoff
    ):
        return CorridorShortcutDecision(
            allowed=False,
            reason="corridor_liveness_unsafe",
            corridor_blocks=corridor_blocks,
        )
    return CorridorShortcutDecision(
        allowed=True,
        reason="exact_witness_live_safe",
        corridor_blocks=corridor_blocks,
    )


__all__ = [
    "CorridorShortcutDecision",
    "block_defined_variables",
    "corridor_shortcut_is_live_safe",
    "evaluate_corridor_shortcut",
    "live_in_variables",
]
