"""Deterministic source-order inventory of MBA rule declarations.

The :class:`VerifiableRule` registry is intentionally not used here.  It is a
runtime registration mechanism whose contents and order can change after a
module reload.  Catalogue receipts need a stable identity, so every source
declaration is listed explicitly in its module order.
"""

from __future__ import annotations

from types import MappingProxyType

from d810.core.typing import Mapping
from d810.mba.rules import (
    add,
    and_,
    bnot,
    cst,
    division,
    eid,
    hodur,
    misc,
    mov,
    mul,
    neg,
    or_,
    predicates,
    sub,
    tigress,
    xor,
)
from d810.mba.rules._base import VerifiableRule


EGRAPH_CLOSED_FAMILIES = frozenset(
    {"add", "xor", "sub", "and", "or", "bnot", "neg", "mul"}
)

FAMILY_REJECTION_REASONS: Mapping[str, str] = MappingProxyType(
    {
        "cst": "constant-folding semantics are not portable",
        "division": "division and cast semantics are not portable",
        "hodur": "profile-specific semantics are not portable",
        "misc": "miscellaneous semantics are not portable",
        "mov": "move and identity semantics are not portable",
        "predicates": "predicate semantics are not portable",
        "tigress": "profile-specific semantics are not portable",
    }
)


MBA_RULE_FAMILIES: Mapping[str, tuple[type[VerifiableRule], ...]] = (
    MappingProxyType(
        {
            "add": (
                add.Add_HackersDelightRule_1,
                add.Add_HackersDelightRule_2,
                add.Add_HackersDelightRule_3,
                add.Add_HackersDelightRule_4,
                add.Add_HackersDelightRule_5,
                add.Add_OllvmRule_1,
                add.Add_OllvmRule_3,
                add.Add_SpecialConstantRule_1,
                add.Add_SpecialConstantRule_2,
                add.Add_SpecialConstantRule_3,
                add.Add_OllvmRule_DynamicConst,
                add.Add_OllvmRule_2,
                add.Add_OllvmRule_4,
                add.AddXor_Rule_1,
                add.AddXor_Rule_2,
            ),
            "and": (
                and_.And_HackersDelightRule_1,
                and_.And_HackersDelightRule_3,
                and_.And_HackersDelightRule_4,
                and_.And_OllvmRule_1,
                and_.And_OllvmRule_3,
                and_.And_FactorRule_2,
                and_.AndBnot_HackersDelightRule_1,
                and_.AndBnot_HackersDelightRule_2,
                and_.AndBnot_FactorRule_1,
                and_.AndBnot_FactorRule_2,
                and_.AndBnot_FactorRule_3,
                and_.AndOr_FactorRule_1,
                and_.AndXor_FactorRule_1,
                and_.And_HackersDelightRule_2,
                and_.And_OllvmRule_2,
                and_.And_FactorRule_1,
                and_.AndBnot_FactorRule_4,
                and_.And1_MbaRule_1,
                and_.AndGetUpperBits_FactorRule_1,
            ),
            "bnot": (
                bnot.Bnot_HackersDelightRule_1,
                bnot.Bnot_HackersDelightRule_2,
                bnot.Bnot_MbaRule_1,
                bnot.Bnot_FactorRule_1,
                bnot.Bnot_FactorRule_4,
                bnot.BnotXor_FactorRule_1,
                bnot.BnotAnd_FactorRule_1,
                bnot.BnotAnd_FactorRule_3,
                bnot.BnotOr_FactorRule_1,
                bnot.Bnot_XorRule_1,
                bnot.Bnot_FactorRule_2,
                bnot.Bnot_FactorRule_3,
                bnot.BnotXor_Rule_1,
                bnot.BnotXor_Rule_2,
                bnot.BnotXor_Rule_3,
                bnot.BnotAnd_FactorRule_2,
                bnot.BnotAnd_FactorRule_4,
                bnot.BnotAdd_MbaRule_1,
                bnot.Bnot_Rule_1,
                bnot.Bnot_FactorRule_5,
            ),
            "cst": (
                cst.CstSimplificationRule1,
                cst.CstSimplificationRule2,
                cst.CstSimplificationRule3,
                cst.CstSimplificationRule4,
                cst.CstSimplificationRule5,
                cst.CstSimplificationRule6,
                cst.CstSimplificationRule7,
                cst.CstSimplificationRule8,
                cst.CstSimplificationRule9,
                cst.CstSimplificationRule10,
                cst.CstSimplificationRule11,
                cst.CstSimplificationRule12,
                cst.CstSimplificationRule13,
                cst.CstSimplificationRule14,
                cst.CstSimplificationRule15,
                cst.CstSimplificationRule16,
                cst.CstSimplificationRule17,
                cst.CstSimplificationRule18,
                cst.CstSimplificationRule19,
                cst.CstSimplificationRule20,
                cst.CstSimplificationRule21,
                cst.CstSimplificationRule22,
            ),
            "division": (division.UnsignedMagicModulo3Rule,),
            "hodur": (
                hodur.Xor_Hodur_1,
                hodur.Bnot_Hodur_1,
                hodur.Or_Hodur_1,
                hodur.Or_Hodur_2,
                hodur.Xor_Hodur_2,
            ),
            "misc": (
                misc.WeirdRule1,
                misc.WeirdRule2,
                misc.WeirdRule3,
                misc.WeirdRule4,
                misc.WeirdRule5,
                misc.WeirdRule6,
            ),
            "mov": (
                mov.GetIdentRule1,
                mov.GetIdentRule2,
                mov.GetIdentRule3,
            ),
            "mul": (
                mul.Mul_MBA_1,
                mul.Mul_MBA_2,
                mul.Mul_MBA_3,
                mul.Mul_MBA_4,
                mul.Mul_FactorRule_1,
                mul.Mul_FactorRule_2,
            ),
            "neg": (
                neg.Neg_HackersDelightRule_1,
                neg.Neg_HackersDelightRule_2,
                neg.NegSub_HackersDelightRule_1,
                neg.NegAdd_HackersDelightRule_1,
                neg.NegAdd_HackersDelightRule_2,
                neg.NegOr_HackersDelightRule_1,
                neg.NegXor_HackersDelightRule_1,
                neg.NegXor_HackersDelightRule_2,
            ),
            "or": (
                or_.Or_HackersDelightRule_2,
                or_.Or_HackersDelightRule_2_variant_1,
                or_.Or_MbaRule_1,
                or_.Or_MbaRule_1_Commuted,
                or_.Or_MbaRule_2,
                or_.Or_MbaRule_3,
                or_.Or_FactorRule_1,
                or_.Or_FactorRule_2,
                or_.Or_Rule_2,
                or_.Or_Rule_4,
                or_.OrBnot_FactorRule_1,
                or_.OrBnot_FactorRule_2,
                or_.Or_HackersDelightRule_1,
                or_.Or_FactorRule_3,
                or_.Or_OllvmRule_1,
                or_.Or_Rule_1,
                or_.Or_Rule_3,
                or_.OrBnot_FactorRule_3,
                or_.OrBnot_FactorRule_4,
            ),
            "predicates": (
                predicates.PredSetnzRule1,
                predicates.PredSetnzRule2,
                predicates.PredSetnzRule3,
                predicates.PredSetnzRule4,
                predicates.PredSetnzRule5,
                predicates.PredSetnzRule6,
                predicates.PredSetnzRule8,
                predicates.PredSetzRule1,
                predicates.PredSetzRule2,
                predicates.PredSetzRule3,
                predicates.PredSetbRule1,
                predicates.Pred0Rule1,
                predicates.Pred0Rule2,
                predicates.Pred0Rule3,
                predicates.Pred0Rule4,
                predicates.Pred0Rule5,
                predicates.Pred0Rule6,
                predicates.Pred0Rule7,
                predicates.PredFFRule1,
                predicates.PredFFRule2,
                predicates.PredFFRule3,
                predicates.PredFFRule4,
                predicates.PredOr2_Rule_1,
                predicates.PredOr1_Rule_1,
                predicates.PredOdd1,
                predicates.PredOdd2,
            ),
            "sub": (
                sub.Sub_HackersDelightRule_1,
                sub.Sub_HackersDelightRule_2,
                sub.Sub_HackersDelightRule_3,
                sub.Sub_HackersDelightRule_4,
                sub.Sub_ComplementMaskHodurRule_1,
                sub.Sub1_FactorRule_1,
                sub.Sub1_FactorRule_2,
                sub.Sub1Add_HackersDelightRule_1,
                sub.Sub1And_HackersDelightRule_1,
                sub.Sub1Or_MbaRule_1,
                sub.Sub1And1_MbaRule_1,
            ),
            "tigress": (
                tigress.TigressIncrementRule,
                tigress.TigressXorViaOrMinusAndRule,
                tigress.TigressAddViaXorOrRule,
                tigress.TigressXorViaSubOrRule,
                tigress.TigressNotEqualSignBitRule,
                tigress.TigressNotEqualSignBitRule64,
                tigress.TigressMultiplyBitPartitionRule,
            ),
            "xor": (
                xor.Xor_HackersDelightRule_1,
                xor.Xor_HackersDelightRule_2,
                xor.Xor_HackersDelightRule_3,
                xor.Xor_HackersDelightRule_4,
                xor.Xor_HackersDelightRule_5,
                eid.Xor_EidKeySchedule_1,
                eid.Xor_EidKeySchedule_2,
                eid.Xor_EidKeySchedule_3,
                xor.Xor_MbaRule_1,
                xor.Xor_MbaRule_2,
                xor.Xor_MbaRule_3,
                xor.Xor_FactorRule_1,
                xor.Xor_FactorRule_2,
                xor.Xor_FactorRule_3,
                xor.Xor_Rule_4,
                xor.Xor_SpecialConstantRule_1,
                xor.Xor_SpecialConstantRule_2,
                xor.Xor1_MbaRule_1,
                xor.Xor_Rule_1,
                xor.Xor_Rule_2,
                xor.Xor_Rule_3,
                xor.XorAlmost_Rule_1,
                xor.Xor_NestedStuff,
                xor.Xor_Rule_4_WithXdu,
            ),
        }
    )
)
