"""Concrete strategies built on top of the shared unflattening engine."""

from d810.passes.bad_while_loop import (
    BAD_WHILE_LOOP_DEPENDENCY_DIAGNOSTICS_METADATA_KEY,
    BAD_WHILE_LOOP_EDITS_METADATA_KEY,
    BAD_WHILE_LOOP_FOLLOW_UP_METADATA_KEY,
    BAD_WHILE_LOOP_CREATE_CONDITIONAL_REDIRECT,
    BAD_WHILE_LOOP_DUPLICATE_AND_REDIRECT,
    BAD_WHILE_LOOP_INSERT_BLOCK,
    BAD_WHILE_LOOP_UNSUPPORTED,
    BadWhileLoopAnalysis,
    BadWhileLoopFollowUp,
    BadWhileLoopGotoConversion,
    BadWhileLoopGotoRedirect,
    BadWhileLoopStrategy,
    build_bad_while_loop_modifications,
    collect_live_bad_while_loop_analysis,
    collect_live_bad_while_loop_edits,
    collect_live_bad_while_loop_follow_up,
    extract_bad_while_loop_dependency_diagnostics,
    extract_bad_while_loop_edits,
    extract_bad_while_loop_follow_up,
    serialize_bad_while_loop_dependency_diagnostics,
    serialize_bad_while_loop_edits,
    serialize_bad_while_loop_follow_up,
)
from d810.passes.fake_jump import (
    FAKE_JUMP_FIXES_METADATA_KEY,
    FakeJumpPredFix,
    FakeJumpResolution,
    FakeJumpStrategy,
    build_fake_jump_modifications,
    extract_fake_jump_fixes,
    resolve_fake_jump_target,
    serialize_fake_jump_fixes,
    should_skip_fake_jump_predecessor,
)
from d810.transforms.guarded_state_machine_planning import (
    build_guarded_state_machine_modifications,
)
from d810.transforms.local_select_loop_planning import build_local_select_loop_modifications
from d810.transforms.side_effect_select_loop_planning import (
    build_side_effect_select_loop_modifications,
)
from d810.analyses.control_flow.guarded_state_machine import (
    GUARDED_STATE_MACHINE_FIXES_METADATA_KEY,
    GuardedStateMachineFix,
    collect_guarded_state_machine_fixes,
    extract_guarded_state_machine_fixes,
    serialize_guarded_state_machine_fixes,
)
from d810.analyses.control_flow.local_select_loop import (
    LOCAL_SELECT_LOOP_FIXES_METADATA_KEY,
    LocalSelectConvergenceLoopFix,
    LocalSelectDirectExitLoopFix,
    LocalSelectLoopCandidate,
    LocalSelectLoopFix,
    LocalSelectTerminalLoopFix,
    collect_local_select_loop_fixes,
    extract_local_select_loop_fixes,
    serialize_local_select_loop_fixes,
)
from d810.analyses.control_flow.side_effect_select_loop import (
    SIDE_EFFECT_SELECT_LOOP_FIXES_METADATA_KEY,
    SideEffectSelectLoopFix,
    collect_side_effect_select_loop_fixes,
    extract_side_effect_select_loop_fixes,
    serialize_side_effect_select_loop_fixes,
)
from d810.passes.guarded_state_machine import GuardedStateMachineStrategy
from d810.passes.local_select_loop import LocalSelectLoopStrategy
from d810.passes.side_effect_select_loop import SideEffectSelectLoopStrategy
from d810.passes.emulated_dispatcher_strategy import (
    DispatcherLoopRecoveryStrategy,
    EMULATED_DISPATCHER_FALLBACK_MODIFICATIONS_KEY,
    EMULATED_DISPATCHER_LOOP_RECOVERY_MODIFICATIONS_KEY,
    EMULATED_DISPATCHER_METADATA_KEY,
    EMULATED_DISPATCHER_MODIFICATIONS_KEY,
    EmulatedDispatcherMetadata,
    EmulatedDispatcherStrategy,
    extract_emulated_dispatcher_fallback_modifications,
    extract_emulated_dispatcher_metadata,
    extract_emulated_dispatcher_modifications,
)
from d810.passes.single_iteration import (
    DEFAULT_MAX_MAGIC,
    DEFAULT_MIN_MAGIC,
    SINGLE_ITERATION_FIXES_METADATA_KEY,
    SingleIterationPredFix,
    SingleIterationStrategy,
    build_single_iteration_modifications,
    extract_single_iteration_fixes,
    serialize_single_iteration_fixes,
)

__all__ = [
    "BAD_WHILE_LOOP_EDITS_METADATA_KEY",
    "BAD_WHILE_LOOP_DEPENDENCY_DIAGNOSTICS_METADATA_KEY",
    "BAD_WHILE_LOOP_FOLLOW_UP_METADATA_KEY",
    "BAD_WHILE_LOOP_CREATE_CONDITIONAL_REDIRECT",
    "BAD_WHILE_LOOP_DUPLICATE_AND_REDIRECT",
    "BAD_WHILE_LOOP_INSERT_BLOCK",
    "BAD_WHILE_LOOP_UNSUPPORTED",
    "BadWhileLoopAnalysis",
    "BadWhileLoopFollowUp",
    "BadWhileLoopGotoConversion",
    "BadWhileLoopGotoRedirect",
    "BadWhileLoopStrategy",
    "DEFAULT_MAX_MAGIC",
    "DEFAULT_MIN_MAGIC",
    "FAKE_JUMP_FIXES_METADATA_KEY",
    "FakeJumpPredFix",
    "FakeJumpResolution",
    "FakeJumpStrategy",
    "GUARDED_STATE_MACHINE_FIXES_METADATA_KEY",
    "LOCAL_SELECT_LOOP_FIXES_METADATA_KEY",
    "SIDE_EFFECT_SELECT_LOOP_FIXES_METADATA_KEY",
    "GuardedStateMachineFix",
    "GuardedStateMachineStrategy",
    "LocalSelectConvergenceLoopFix",
    "LocalSelectDirectExitLoopFix",
    "LocalSelectLoopCandidate",
    "LocalSelectLoopFix",
    "LocalSelectLoopStrategy",
    "LocalSelectTerminalLoopFix",
    "SideEffectSelectLoopFix",
    "SideEffectSelectLoopStrategy",
    "EMULATED_DISPATCHER_METADATA_KEY",
    "EMULATED_DISPATCHER_MODIFICATIONS_KEY",
    "EMULATED_DISPATCHER_FALLBACK_MODIFICATIONS_KEY",
    "EMULATED_DISPATCHER_LOOP_RECOVERY_MODIFICATIONS_KEY",
    "DispatcherLoopRecoveryStrategy",
    "EmulatedDispatcherMetadata",
    "EmulatedDispatcherStrategy",
    "SINGLE_ITERATION_FIXES_METADATA_KEY",
    "SingleIterationPredFix",
    "SingleIterationStrategy",
    "build_bad_while_loop_modifications",
    "build_fake_jump_modifications",
    "build_guarded_state_machine_modifications",
    "build_local_select_loop_modifications",
    "build_side_effect_select_loop_modifications",
    "collect_guarded_state_machine_fixes",
    "collect_local_select_loop_fixes",
    "collect_side_effect_select_loop_fixes",
    "build_single_iteration_modifications",
    "collect_live_bad_while_loop_analysis",
    "collect_live_bad_while_loop_edits",
    "collect_live_bad_while_loop_follow_up",
    "extract_bad_while_loop_dependency_diagnostics",
    "extract_bad_while_loop_edits",
    "extract_bad_while_loop_follow_up",
    "extract_fake_jump_fixes",
    "extract_guarded_state_machine_fixes",
    "extract_local_select_loop_fixes",
    "extract_side_effect_select_loop_fixes",
    "extract_emulated_dispatcher_fallback_modifications",
    "extract_emulated_dispatcher_metadata",
    "extract_emulated_dispatcher_modifications",
    "extract_single_iteration_fixes",
    "resolve_fake_jump_target",
    "serialize_bad_while_loop_dependency_diagnostics",
    "serialize_bad_while_loop_edits",
    "serialize_bad_while_loop_follow_up",
    "serialize_fake_jump_fixes",
    "serialize_guarded_state_machine_fixes",
    "serialize_local_select_loop_fixes",
    "serialize_side_effect_select_loop_fixes",
    "serialize_single_iteration_fixes",
    "should_skip_fake_jump_predecessor",
]
